// Auto-generated by deploy.sh — do not edit manually
const API_BASE = 'http://aizesk-alb-1650909979.us-east-1.elb.amazonaws.com';

export const environment = {
  production: true,
  apiUrls: {
    auth: `${API_BASE}/api/v1/auth`,
    users: `${API_BASE}/api/v1/users`,
    transactions: `${API_BASE}/api/v1/transactions`,
    reporting: `${API_BASE}/api/v1/reports`,
    subscriptions: `${API_BASE}/api/v1/subscriptions`,
    platforms: `${API_BASE}/api/v1/platforms`,
    notifications: `${API_BASE}/api/v1/notifications`,
  },
  notificationsWs: `ws://aizesk-alb-1650909979.us-east-1.elb.amazonaws.com/ws/notifications`,
  googleClientId: '765392548979-hg2npq98sdd30c2jossmc0nh7uoj0jmh.apps.googleusercontent.com',
};
